### ISSUE TITLE
Update conda-forge and astropy conda packages to 0.3.2

### ISSUE THREAD

**Issue by hugobuddel** [astropy/pytest-remotedata#47]
The [conda packages for pytest-remotedata on the conda-forge and astropy channels](https://anaconda.org/search?q=pytest-remotedata) are still 0.3.1. The package on anaconda and main is 0.3.2.

These do not incorporate [the `LooseVersion` change](https://github.com/astropy/pytest-remotedata/commit/f531c42f7380f8f6738fcfd7a4649fd49e45d876) and therefore fail with [pytest 6.0.0rc1](https://github.com/pytest-dev/pytest/releases/tag/6.0.0rc1) that was released last week (because "6.0.0rc1" is not a StrictVersion).

Can we therefore upgrade the astropy and conda-forge versions to 0.3.2? Or perhaps just remove them altogether? (As it seems that the anaconda channel has all versions of pytest-remotedata anyway.)

Some of CI runs broke because we had conda-forge as a higher priority channel than anaconda ('defaults') and did not specify a version. We have now hardcoded pytest-remotedata 0.3.2 (or higher) as a depency, so it will automatically pickup the anaconda one anyway and our immediate problem is solved.

Pytest 6.0.0 will probably be released soon too, which will also resolve the problem (until some other rc version is released).

**Comment by pllim** [comment]
@mwcraig , do you handle the conda releases for this package? Thanks.

**Comment by mwcraig** [comment]
@pllim -- yes; will make a couple changes to https://github.com/conda-forge/pytest-remotedata-feedstock/pull/6 later today and then merge. Needs some dependency updates and maybe a couple more things.

Thanks for the ping!

**Comment by mwcraig** [comment]
I just merged https://github.com/conda-forge/pytest-remotedata-feedstock/pull/6 which should fix this. It will be roughly ~1 hour until it shows up in conda.

**Comment by pllim** [comment]
Thank you!

**Comment by hugobuddel** [comment]
https://anaconda.org/search?q=pytest-remotedata still shows 0.31 for the conda-forge and astropy channels. The specific problem with pytest is gone though, because they released 6.0.0 and later.

**Comment by mwcraig** [comment]
Working on the fix....

**Comment by mwcraig** [comment]
Fixed now, thanks for reporting.
